# Site
repository: TianKiat/TianKiat.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Ng Tian Kiat
title: Computer Science Undergraduate
email: ngtiankiat97@gmail.com
website: https://tiankiat.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  TianKiat
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: tiankiatng
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi! <i class="fa-light fa-hand-wave"></i> I am Tian Kiat, a software developer with 4 years of experience in game development with an interest in AI and data analytics.
  I have made games using game engines built from scratch with C/C++/C# and commercial game engines such as Unity and Unreal.

  I strongly believe that the curiousity and the drive to never stop learning is the key to success.
  No one starts out as an expert in anything - the discipline and humility to learn the ropes is how you achieve self-actualization.
  
  During my study in DigiPen, I have gained an interest and curiousity in AI and data analytics. With a strong foundation in linear algebra, calculus
  and statistics, I am very keen to research and learn more about AI techniques and applying them in software and business contexts.


  Things I have done: Develop games, apps, ML models, BI dashboards, RPA robots.

  Things I want to do: Anything I find interesting!

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Bogos Binted
        # link_text: Project Website
        additional_links:
          - title: DigiPen 3D Game Project
            icon: fab fa-google-drive
            url: https://drive.google.com/file/d/1--vY17V-EgJs2cNvy4gAUTknxny2golQ/view?usp=drivesdk
        quote: >
          A 3D Wacky Sci-fi shooter game built using a custom C++ and C# engine. 
        description: | # this will include new lines to allow paragraphs
          This project is the final capstone project from my time in DigiPen. A 8-man project involving programmers and game designers.
          I was in charge of writing the C++ API and data structures that binded onto our C# scripting layer. I was also the main gameplay programmer.
          
          My main job as a gameplay programmer is to implement a 3D spline system that the player and enemies follow, as well as, create
          a "choreography" system for scripting of the combat of the game. This included spawning, moving between waypoints and timing of
          attack patterns of enemies seen in the game.
      - layout: top-middle
        title: Deep Learning Image Classification
        # link_text: Project Website
        additional_links:
          - title:  TianKiat/ML-Naive-Bees
            icon: fab fa-github
            url: github.com/TianKiat/ML-Naive-Bees
        quote: >
          Using deep learning networks to classify images of BEES!
        description: | # this will include new lines to allow paragraphs
          This project along with my other ML projects was done as part of my elective focus on AI. I learned a lot about traditional models in ML,
          and in this project I built a CNN image classifier. I learned a lot about <mark>Keras</mark> in this project.
          
          This is just the start in my journey to learn more about ML and I look forward to researching
          and applying more novel solutions to solve real world problems!
      - layout: top-middle
        title: DC Metro Crime Data Exploration and Visualization
        # link_text: Project Website
        additional_links:
          - title: TianKiat/dc-crime-data-exploration
            icon: fab fa-github
            url: github.com/TianKiat/dc-crime-data-exploration
        quote: >
          Learning Pandas, Seaborn and applying what I learned!
        description: | # this will include new lines to allow paragraphs
          I started this exercise to apply my knowledge of <mark>Pandas</mark> and <mark>Seaborn</mark> outside of school assignments. I focused on exploring and creating visuals that
          would aid in hypothesis testing and providing insights to the trends given in the dataset. 
          
          From this project, I learned to be more client and goal focused
          when building visualizations, as it is always about telling a story with the huge amounts of data you get.
      - layout: top-middle
        title: Robotic Process Automation (RPA) processes for PSA Singapore
        quote: >
          Developing and deploying RPA robots to aid PSA Singapore's Container Business Division.
        description: | # this will include new lines to allow paragraphs
          During my internship in PSA Singapore, I was part of the Container Business Division's Process Re-engineering department.
          In this department, I was put in-charge of developing RPA robots using UiPath that would be rolled out to the different
          terminals in PSA's ports in order to reduce man-hours needed in completing repititive tasks.

          Projects:
          - Automating data entry for containers' extra-activities into business portal
          - Automating report generation to flag low-occupancy yard slots to optimize yard movement planning.
          - Creating Power BI workshop manual with detailed instructions for collecting, cleaning and visualizing data in Power BI dashboards.


  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: PSA Singapore
        link: www.singaporepsa.com
        link_text: PSA Singapore
        sub_title: Robotics Process Developer and Data Analyst
        caption: May 2022 - Present
        quote: >
          Automating business process and building dashboards by analysing business data.
        description: | # this will include new lines to allow paragraphs
            This internship was extremely fruitful as I got to deploy RPA processes across PSA Singapore's terminals saving at least 100+ man hours annually.
            In addition, I was able to conduct and supply teaching materials for data analytics and dashboard building workshops.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: DigiPen Institute of Technology Singapore
        caption: 2019 - 2022
        sub_title: BSc Computer Science and Game Design
        quote: >
          I was able to combine my love of games with my passion in computer science, this gave be the drive to learn and explore!
        description: | # this will include new lines to allow paragraphs
          During my time in DigiPen, I was able to establish a strong foundation in computer science and mathematics. Due to the practical approach of my course,
          I also gained skills and experience in teamwork, communication, critical problem solving and project management.
      - layout: left
        title: Ngee Ann Polytechnic
        caption: 2014 - 2017
        sub_title: Diploma in Multimedia & Animation
        quote: >
          I was discovering my passion for technology and software.
        description: | # this will include new lines to allow paragraphs
          While studying in Ngee Ann, I was given many opportunites to explore and try out things in the arts/design, as well as, information technology
          because my course was in Multimedia. I explored website design, game design, game programming, ArcViz, 3D game animation.

  - title: More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Some of my hobbies and interest are:
      - Fishing
      - Cycling
      - Gym & Calisthenics
      - *Never ending list of random hobbies I am bad at but enjoy* <i class="fa-light fa-face-awesome"></i>

     # Look at this cool image  
     # ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
